sudo: required
services:
 - docker

before_install:
 - docker build -t test1 -f Dockerfile.dev .

script:
  - docker run -e CI=true test1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "GolanDocker"
  env: "Golandocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-318550661249"
  bucket_path: "GolanDocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
